# Do not edit this file. Unless you're the developer.

dUtilities:
  type: world
  version: 0.0.1
  events:
    on version command:
      - if <context.args.get[1]||null> == dUtilities:
        - narrate <script.yaml_key[version]>
        - determine fulfilled
#    on reload scripts:
#      - inject dUtilitiesInit

#    on server start:
#      - inject dUtilitiesInit
