# Do not edit this file. Unless you're the developer.

dUtilities_version:
  type: world
  version: 1.1.1
  events:
    on version command:
      - if <context.args.get[1]||null> == dUtilities:
        - narrate <script.yaml_key[version]>
        - determine fulfilled
